services:
  - type: web
    name: playto-community-feed-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn community_feed.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: community_feed.settings
      - key: DATABASE_URL
        fromDatabase:
          name: playto-community-feed-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "playto-community-feed-backend.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://playto-community-feed.vercel.app,http://localhost:3000"

databases:
  - name: playto-community-feed-db
    databaseName: playto_community_feed
    user: playto_user